# Generated by Django 4.2.7 on 2023-12-07 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='pincode',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(6)]),
        ),
    ]
